-- Mage Knight Highly Scripted source entry point.
-- Sebastian's TTS Editor bundles these modules into the single Global.lua sent to Tabletop Simulator.

require("Data")
require("Shared")
require("SetupInterface")
require("PlayingGame.Help")
require("PlayingGame.PlayerBoard.Deeds")
require("SetupGame")
require("PlayingGame.Quests")
require("PlayingGame.City")
require("PlayingGame")
require("PlayingGame.PlayerBoard.Skills")
require("PlayingGame.PlayerBoard.PuppetMaster")
require("PlayingGame.Combat")
require("PlayingGame.Turn")
require("PlayingGame.Scenario")
require("PlayingGame.Scoring")
require("PlayingGame.AI.Common")
require("PlayingGame.AI.Proxy")
require("PlayingGame.AI.Dummy")
require("PlayingGame.AI.Volkare")
require("PlayingGame.Movement")
require("PlayingGame.Rollers")
require("PlayingGame.UI")
require("PlayingGame.Events")
require("PlayingGame.Callbacks")
require("PlayingGame.Integration")
